MangoV2/mango.web.frontend/Controllers/AuthController.cs
using mango.web.frontend.Models;
using mango.web.frontend.Models.WebDTO;
using mango.web.frontend.Services.Iservices;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using mango.web.frontend.Utility;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Serilog;

namespace mango.web.frontend.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService authService;
        private readonly ITokenProvider _tokenProvider;
        //private readonly ILogger<AuthController> _logger;
        public AuthController(IAuthService authService, ITokenProvider tokenProvider/*, ILogger<AuthController> logger*/)
        {
            this.authService = authService;
            _tokenProvider = tokenProvider;
            //_logger = logger;
        }
        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDto loginRequestDto = new();
            Log.Information("{User} accessed the Login page.", User.Identity.Name);
            return View(loginRequestDto);
        }
        
        [HttpGet]
        public IActionResult Register()
        {
            Log.Information("{User} accessed the Register page.", User.Identity.Name);

            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.RoleAdmin,Value=SD.RoleAdmin},
                new SelectListItem{Text=SD.RoleCustomer,Value=SD.RoleCustomer},
            };

            ViewBag.RoleList = roleList;
            

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegistrationRequestDto obj)
        {
            //Console.WriteLine("Register Get Second Method");
            try
            {
                Log.Information("{User} submitted registration form.", User.Identity.Name);

                WebAPIResponse responseDto = await authService.RegisterAsync<WebAPIResponse>(obj);
                WebAPIResponse assignRole;
                //get the urk 
                //string check = SD.AuthAPIBase.TrimEnd('/') + "/api/AuthAPI/Register";
                //Console.WriteLine("Url is:" + check);

                if (responseDto != null && responseDto.IsSuccess)
                {
                    //print responseDTO valus
                    //Console.WriteLine(" inner method Response DTO: " + JsonConvert.SerializeObject(responseDto));
                    if (string.IsNullOrEmpty(obj.Role))
                    {
                        obj.Role = SD.RoleCustomer;
                        //print obj.Role
                        //Console.WriteLine("Role is:" + obj.Role);
                    }
                    assignRole = await authService.AssignRoleAsync<WebAPIResponse>(obj.Email, obj.Role);
                    //print assignRole
                    //Console.WriteLine("Assign Role: " + JsonConvert.SerializeObject(assignRole));
                    if (assignRole != null && assignRole.IsSuccess)
                    {
                        TempData["success"] = "Registration Successful";
                        Log.Information($"Registration successful. Email: {obj.Email}");
                        //Console.WriteLine($"Registration successful. Email: {obj.Email}");
                        return RedirectToAction("Login");
                    }
                }
                else
                {
                    Log.Warning($"Registration failed. Errors: {string.Join(", ", responseDto.ErrorMessages)}");
                    TempData["error"] = string.Join(", ", responseDto.ErrorMessages);

                }

                var roleList = new List<SelectListItem>()
        {
            new SelectListItem{Text=SD.RoleAdmin,Value=SD.RoleAdmin},
            new SelectListItem{Text=SD.RoleCustomer,Value=SD.RoleCustomer},
        };

                ViewBag.RoleList = roleList;

                return View(obj);
            }
            catch (Exception ex)
            {
                Log.Error($"An exception occurred during registration: {ex.Message}");
                // Optionally, you can log the stack trace as well: _logger.LogError($"StackTrace: {ex.StackTrace}");
                TempData["error"] = $"An unexpected error occurred during registration.";
                return View(obj);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDto loginRequestDto)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    var response = await authService.LoginAsync<WebAPIResponse>(loginRequestDto);

                    if (response.IsSuccess && response != null)
                    {
                        // Handle successful login, e.g., set authentication cookie, redirect to dashboard
                        // You may use _tokenProvider to generate and manage tokens
                        LoginResponseDto loginResponseDto =
                            JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(response.Result));

                        await SignInUser(loginResponseDto);
                        _tokenProvider.SetToken(loginResponseDto.Token);
                        Log.Information("User {Username} logged in successfully. Token: {Token}", loginRequestDto.UserName, loginResponseDto.Token);
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        Log.Warning("User {Username} login failed. Error: {ErrorMessages}", loginRequestDto.UserName, string.Join(", ", response.ErrorMessages));

                        // Handle unsuccessful login, display error messages to the user
                        //_logger.LogWarning("Login failed. Errors:");
                        foreach (var errorMessage in response.ErrorMessages)
                        {
                            ModelState.AddModelError(string.Empty, errorMessage);
                            Log.Warning(errorMessage);
                        }

                    }
                }

                Log.Warning($"Invalid login request. Username: {loginRequestDto.UserName}");
                return View(loginRequestDto);
            }
            catch (Exception ex)
            {
                Log.Error($"An exception occurred during login: {ex.Message}");
                // Optionally, you can log the stack trace as well: _logger.LogError($"StackTrace: {ex.StackTrace}");
                ModelState.AddModelError(string.Empty, $"An unexpected error occurred during login.");
                return View(loginRequestDto);
            }
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            try
            {
                // Sign out the user
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                _tokenProvider.ClearToken();
                Log.Information("User {Username} logged out.", User.Identity.Name);
                // Optionally, you can redirect the user to a specific page after logout
                return RedirectToAction("Index", "Home");
            }
            catch(Exception ex)
            {
                Log.Error(ex, "An exception occurred during logout: {ErrorMessage}", ex.Message);
                return RedirectToAction("Index", "Home");
            }
        }


        

        private async Task SignInUser(LoginResponseDto model)
        {
            var handler = new JwtSecurityTokenHandler();

            var jwt = handler.ReadJwtToken(model.Token);

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));


            identity.AddClaim(new Claim(ClaimTypes.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(ClaimTypes.Role,
                jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));



            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
        }

    }
}

MangoV2/mango.web.frontend/Controllers/CouponController.cs
using mango.web.frontend.Models;
using mango.web.frontend.Models.VM;
using mango.web.frontend.Models.WebDTO;
using mango.web.frontend.Services.Iservices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Serilog;
namespace mango.web.frontend.Controllers
{
    public class CouponController : Controller
    {

        private readonly ICouponService _couponService;

        //constructor for the controller
        public CouponController(ICouponService couponService)
        {

            _couponService = couponService;
        }

        // GET
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> CouponIndex()
        {
            try
            {
                Log.Information("Accessing Coupon Index page.");

                List<CouponViewModel> list = new List<CouponViewModel>();
                var response = await _couponService.GetAllCouponAsync<WebAPIResponse>();
                Log.Information("Response is: {@Response}", response);
                //Console.WriteLine($"Response Content: {JsonConvert.SerializeObject(response)}");

                if (response != null && response.IsSuccess)
                {
                    list = JsonConvert.DeserializeObject<List<CouponViewModel>>(response.Result.ToString()) ?? new List<CouponViewModel>();

                    foreach (var coupon in list)
                    {
                        Log.Information("Coupon Code: {CouponCode}, Min Amount: {MinAmount}", coupon.CouponCode, coupon.MinAmount);
                    }
                }

                return View(list);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "An error occurred while accessing the Coupon Index page.");
                throw; // You may handle the exception according to your application's error handling strategy
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCoupon(CreateCouponDTO model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var response = await _couponService.CreateCouponAsync<WebAPIResponse>(model);
                    if (response != null && response.IsSuccess)
                    {
                        Log.Information("Coupon Created Successfully");
                        TempData["success"] = "Coupon Created Successfully";
                        return RedirectToAction(nameof(CouponIndex));
                    }
                    TempData["error"] = "Error Encountered";
                }

                return View("CreateCoupon", model);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "An error occurred while creating a coupon.");
                throw; // You may handle the exception according to your application's error handling strategy
            }
        }



        public async Task<IActionResult> CreateCoupon()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> UpdateCoupon(int couponId)
        {
            try
            {
                Log.Information("Update Coupon Method for CouponId: {CouponId}", couponId);

                var response = await _couponService.GetCouponByIdAsync<WebAPIResponse>(couponId);
                Log.Information("Response is: {@Response}", response);

                if (response != null && response.IsSuccess)
                {
                    var coupon = JsonConvert.DeserializeObject<CouponViewModel>(response.Result.ToString());
                    Log.Information("Coupon Code: {CouponCode}, Min Amount: {MinAmount}", coupon.CouponCode, coupon.MinAmount);

                    var updateCouponDto = new UpdateCouponDTO
                    {
                        CouponId = coupon.CouponId,
                        CouponCode = coupon.CouponCode,
                        DiscountAmount = coupon.DiscountAmount,
                        MinAmount = coupon.MinAmount
                    };

                    return View(updateCouponDto);
                }

                TempData["error"] = "Coupon not found.";
                return RedirectToAction(nameof(CouponIndex));
            }
            catch (Exception ex)
            {
                Log.Error(ex, "An error occurred while updating the coupon for CouponId: {CouponId}", couponId);
                throw; // You may handle the exception according to your application's error handling strategy
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateCoupon(UpdateCouponDTO model)
        {
            try
            {
                Log.Information("Update Coupon");

                if (ModelState.IsValid)
                {
                    var response = await _couponService.UpdateCouponAsync<WebAPIResponse>(model);
                    if (response != null && response.IsSuccess)
                    {
                        Log.Information("Coupon Updated Successfully");
                        TempData["success"] = "Coupon Updated Successfully";
                        return RedirectToAction(nameof(CouponIndex));
                    }

                    TempData["error"] = "Error Encountered";
                }

                return View(model);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "An error occurred while updating the coupon.");
                throw; // You may handle the exception according to your application's error handling strategy
            }
        }

        [HttpGet]
        public async Task<IActionResult> DeleteCoupon(int couponId)
        {
            try
            {
                Log.Information("Delete Coupon Method for CouponId: {CouponId}", couponId);

                var response = await _couponService.GetCouponByIdAsync<WebAPIResponse>(couponId);

                if (response != null && response.IsSuccess)
                {
                    var coupon = JsonConvert.DeserializeObject<CouponViewModel>(response.Result.ToString());
                    var deleteCouponDto = new DeleteCouponDTO
                    {
                        CouponId = coupon.CouponId,
                        CouponCode = coupon.CouponCode,
                        DiscountAmount = coupon.DiscountAmount,
                        MinAmount = coupon.MinAmount
                    };

                    return View(deleteCouponDto);
                }

                TempData["error"] = "Coupon not found.";
                return RedirectToAction(nameof(CouponIndex));
            }
            catch (Exception ex)
            {
                Log.Error(ex, "An error occurred while deleting the coupon for CouponId: {CouponId}", couponId);
                throw; // You may handle the exception according to your application's error handling strategy
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCoupon(DeleteCouponDTO model)
        {
            try
            {
                Log.Information("Delete Coupon");

                if (ModelState.IsValid)
                {
                    var response = await _couponService.DeleteCouponAsync<WebAPIResponse>(model.CouponId);
                    if (response != null && response.IsSuccess)
                    {
                        Log.Information("Coupon Deleted Successfully");
                        TempData["success"] = "Coupon Deleted Successfully";
                        return RedirectToAction(nameof(CouponIndex));
                    }

                    TempData["error"] = "Error Encountered";
                }

                return View(model);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "An error occurred while deleting the coupon.");
                throw; // You may handle the exception according to your application's error handling strategy
            }
        }
    }
    }

MangoV2/mango.web.frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MangoWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MangoWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mango.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-page="/Home/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="@Url.Action("CouponIndex", "Coupon")">Coupon</a>
                                <a class="dropdown-item" href="@Url.Action("ProductIndex", "Product")">Product</a>

                                <li><hr class="dropdown-divider"></li>

                            </ul>
                        </li>
                       <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="CartIndex">
                                &nbsp;<i class="bi bi-cart"></i>&nbsp;
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">Hello @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Auth" asp-action="Logout">
                                    @Html.AntiForgeryToken()
                                    <button type="submit" class="nav-link btn btn-link">Logout</button>
                                </form>
                            </li>

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notofication" />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MangoWeb - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MangoV2/mango.web.frontend/Views/Shared/_Notofication.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@if(TempData["success"]!=null)
{
    <script type="text/javascript">       
        Swal.fire({
            position: "top-end",
            icon: "success",
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 1500,
            timerProgressBar: true
        });
    </script>
}
@if(TempData["error"]!=null)
{
    <script type="text/javascript">
        Swal.fire({
            position: "top-end",
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 3000, 
            timerProgressBar: true
        })
    </script>
}